# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/janus_turnout.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/janus_turnout.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1aprotos/janus_turnout.proto\"8\n\x0f\x44\x65viceCondition\x12\x18\n\x10\x64\x65vice_condition\x18\x01 \x01(\r\x12\x0b\n\x03\x61id\x18\x02 \x01(\t\"G\n\x10\x41ttestationState\x12\x19\n\x11\x61ttestation_state\x18\x01 \x01(\r\x12\x0b\n\x03\x61id\x18\x02 \x01(\t\x12\x0b\n\x03vid\x18\x03 \x01(\tb\x06proto3')
)




_DEVICECONDITION = _descriptor.Descriptor(
  name='DeviceCondition',
  full_name='DeviceCondition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_condition', full_name='DeviceCondition.device_condition', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aid', full_name='DeviceCondition.aid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=86,
)


_ATTESTATIONSTATE = _descriptor.Descriptor(
  name='AttestationState',
  full_name='AttestationState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='attestation_state', full_name='AttestationState.attestation_state', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aid', full_name='AttestationState.aid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vid', full_name='AttestationState.vid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=159,
)

DESCRIPTOR.message_types_by_name['DeviceCondition'] = _DEVICECONDITION
DESCRIPTOR.message_types_by_name['AttestationState'] = _ATTESTATIONSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeviceCondition = _reflection.GeneratedProtocolMessageType('DeviceCondition', (_message.Message,), dict(
  DESCRIPTOR = _DEVICECONDITION,
  __module__ = 'protos.janus_turnout_pb2'
  # @@protoc_insertion_point(class_scope:DeviceCondition)
  ))
_sym_db.RegisterMessage(DeviceCondition)

AttestationState = _reflection.GeneratedProtocolMessageType('AttestationState', (_message.Message,), dict(
  DESCRIPTOR = _ATTESTATIONSTATE,
  __module__ = 'protos.janus_turnout_pb2'
  # @@protoc_insertion_point(class_scope:AttestationState)
  ))
_sym_db.RegisterMessage(AttestationState)


# @@protoc_insertion_point(module_scope)
