# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: janus_audit.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='janus_audit.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11janus_audit.proto\"V\n\x0c\x41uditRequest\x12\x0c\n\x04ssid\x18\x01 \x03(\t\x12\x0c\n\x04\x66lag\x18\x02 \x01(\r\x12\x10\n\x08\x61udit_id\x18\x03 \x01(\t\x12\x0b\n\x03\x61id\x18\x04 \x01(\t\x12\x0b\n\x03vid\x18\x05 \x01(\t\"\\\n\x0f\x41uditCredential\x12\r\n\x05nonce\x18\x01 \x01(\t\x12\x12\n\ncredential\x18\x02 \x01(\t\x12\x0b\n\x03\x61id\x18\x03 \x01(\t\x12\x0b\n\x03vid\x18\x04 \x01(\t\x12\x0c\n\x04ssid\x18\x05 \x01(\t\"+\n\x0b\x41uditResult\x12\x0e\n\x06result\x18\x01 \x01(\r\x12\x0c\n\x04ssid\x18\x02 \x01(\tb\x06proto3')
)




_AUDITREQUEST = _descriptor.Descriptor(
  name='AuditRequest',
  full_name='AuditRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ssid', full_name='AuditRequest.ssid', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flag', full_name='AuditRequest.flag', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='audit_id', full_name='AuditRequest.audit_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aid', full_name='AuditRequest.aid', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vid', full_name='AuditRequest.vid', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=107,
)


_AUDITCREDENTIAL = _descriptor.Descriptor(
  name='AuditCredential',
  full_name='AuditCredential',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nonce', full_name='AuditCredential.nonce', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='credential', full_name='AuditCredential.credential', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aid', full_name='AuditCredential.aid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vid', full_name='AuditCredential.vid', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ssid', full_name='AuditCredential.ssid', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=201,
)


_AUDITRESULT = _descriptor.Descriptor(
  name='AuditResult',
  full_name='AuditResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='AuditResult.result', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ssid', full_name='AuditResult.ssid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=246,
)

DESCRIPTOR.message_types_by_name['AuditRequest'] = _AUDITREQUEST
DESCRIPTOR.message_types_by_name['AuditCredential'] = _AUDITCREDENTIAL
DESCRIPTOR.message_types_by_name['AuditResult'] = _AUDITRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AuditRequest = _reflection.GeneratedProtocolMessageType('AuditRequest', (_message.Message,), dict(
  DESCRIPTOR = _AUDITREQUEST,
  __module__ = 'janus_audit_pb2'
  # @@protoc_insertion_point(class_scope:AuditRequest)
  ))
_sym_db.RegisterMessage(AuditRequest)

AuditCredential = _reflection.GeneratedProtocolMessageType('AuditCredential', (_message.Message,), dict(
  DESCRIPTOR = _AUDITCREDENTIAL,
  __module__ = 'janus_audit_pb2'
  # @@protoc_insertion_point(class_scope:AuditCredential)
  ))
_sym_db.RegisterMessage(AuditCredential)

AuditResult = _reflection.GeneratedProtocolMessageType('AuditResult', (_message.Message,), dict(
  DESCRIPTOR = _AUDITRESULT,
  __module__ = 'janus_audit_pb2'
  # @@protoc_insertion_point(class_scope:AuditResult)
  ))
_sym_db.RegisterMessage(AuditResult)


# @@protoc_insertion_point(module_scope)
