/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: janus_attestation.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "janus_attestation.pb-c.h"
void   challenge__init
                     (Challenge         *message)
{
  static const Challenge init_value = CHALLENGE__INIT;
  *message = init_value;
}
size_t challenge__get_packed_size
                     (const Challenge *message)
{
  assert(message->base.descriptor == &challenge__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t challenge__pack
                     (const Challenge *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &challenge__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t challenge__pack_to_buffer
                     (const Challenge *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &challenge__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Challenge *
       challenge__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Challenge *)
     protobuf_c_message_unpack (&challenge__descriptor,
                                allocator, len, data);
}
void   challenge__free_unpacked
                     (Challenge *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &challenge__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   report__init
                     (Report         *message)
{
  static const Report init_value = REPORT__INIT;
  *message = init_value;
}
size_t report__get_packed_size
                     (const Report *message)
{
  assert(message->base.descriptor == &report__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t report__pack
                     (const Report *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &report__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t report__pack_to_buffer
                     (const Report *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &report__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Report *
       report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Report *)
     protobuf_c_message_unpack (&report__descriptor,
                                allocator, len, data);
}
void   report__free_unpacked
                     (Report *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &report__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   verify__init
                     (Verify         *message)
{
  static const Verify init_value = VERIFY__INIT;
  *message = init_value;
}
size_t verify__get_packed_size
                     (const Verify *message)
{
  assert(message->base.descriptor == &verify__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t verify__pack
                     (const Verify *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &verify__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t verify__pack_to_buffer
                     (const Verify *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &verify__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Verify *
       verify__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Verify *)
     protobuf_c_message_unpack (&verify__descriptor,
                                allocator, len, data);
}
void   verify__free_unpacked
                     (Verify *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &verify__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   att_result__init
                     (AttResult         *message)
{
  static const AttResult init_value = ATT_RESULT__INIT;
  *message = init_value;
}
size_t att_result__get_packed_size
                     (const AttResult *message)
{
  assert(message->base.descriptor == &att_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t att_result__pack
                     (const AttResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &att_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t att_result__pack_to_buffer
                     (const AttResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &att_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AttResult *
       att_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AttResult *)
     protobuf_c_message_unpack (&att_result__descriptor,
                                allocator, len, data);
}
void   att_result__free_unpacked
                     (AttResult *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &att_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor challenge__field_descriptors[3] =
{
  {
    "nonce",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Challenge, nonce),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aid",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Challenge, aid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vid",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Challenge, vid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned challenge__field_indices_by_name[] = {
  1,   /* field[1] = aid */
  0,   /* field[0] = nonce */
  2,   /* field[2] = vid */
};
static const ProtobufCIntRange challenge__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor challenge__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Challenge",
  "Challenge",
  "Challenge",
  "",
  sizeof(Challenge),
  3,
  challenge__field_descriptors,
  challenge__field_indices_by_name,
  1,  challenge__number_ranges,
  (ProtobufCMessageInit) challenge__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor report__field_descriptors[2] =
{
  {
    "payload",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Report, payload),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aid",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Report, aid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned report__field_indices_by_name[] = {
  1,   /* field[1] = aid */
  0,   /* field[0] = payload */
};
static const ProtobufCIntRange report__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor report__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Report",
  "Report",
  "Report",
  "",
  sizeof(Report),
  2,
  report__field_descriptors,
  report__field_indices_by_name,
  1,  report__number_ranges,
  (ProtobufCMessageInit) report__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor verify__field_descriptors[2] =
{
  {
    "vid",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Verify, vid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aid",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Verify, n_aid),
    offsetof(Verify, aid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned verify__field_indices_by_name[] = {
  1,   /* field[1] = aid */
  0,   /* field[0] = vid */
};
static const ProtobufCIntRange verify__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor verify__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Verify",
  "Verify",
  "Verify",
  "",
  sizeof(Verify),
  2,
  verify__field_descriptors,
  verify__field_indices_by_name,
  1,  verify__number_ranges,
  (ProtobufCMessageInit) verify__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor att_result__field_descriptors[2] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AttResult, result),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vid",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AttResult, vid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned att_result__field_indices_by_name[] = {
  0,   /* field[0] = result */
  1,   /* field[1] = vid */
};
static const ProtobufCIntRange att_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor att_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AttResult",
  "AttResult",
  "AttResult",
  "",
  sizeof(AttResult),
  2,
  att_result__field_descriptors,
  att_result__field_indices_by_name,
  1,  att_result__number_ranges,
  (ProtobufCMessageInit) att_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
