/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: janus_turnout.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "janus_turnout.pb-c.h"
void   device_condition__init
                     (DeviceCondition         *message)
{
  static const DeviceCondition init_value = DEVICE_CONDITION__INIT;
  *message = init_value;
}
size_t device_condition__get_packed_size
                     (const DeviceCondition *message)
{
  assert(message->base.descriptor == &device_condition__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t device_condition__pack
                     (const DeviceCondition *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &device_condition__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t device_condition__pack_to_buffer
                     (const DeviceCondition *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &device_condition__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DeviceCondition *
       device_condition__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DeviceCondition *)
     protobuf_c_message_unpack (&device_condition__descriptor,
                                allocator, len, data);
}
void   device_condition__free_unpacked
                     (DeviceCondition *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &device_condition__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   attestation_state__init
                     (AttestationState         *message)
{
  static const AttestationState init_value = ATTESTATION_STATE__INIT;
  *message = init_value;
}
size_t attestation_state__get_packed_size
                     (const AttestationState *message)
{
  assert(message->base.descriptor == &attestation_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t attestation_state__pack
                     (const AttestationState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &attestation_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t attestation_state__pack_to_buffer
                     (const AttestationState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &attestation_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AttestationState *
       attestation_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AttestationState *)
     protobuf_c_message_unpack (&attestation_state__descriptor,
                                allocator, len, data);
}
void   attestation_state__free_unpacked
                     (AttestationState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &attestation_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor device_condition__field_descriptors[2] =
{
  {
    "device_condition",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DeviceCondition, device_condition),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aid",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceCondition, aid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned device_condition__field_indices_by_name[] = {
  1,   /* field[1] = aid */
  0,   /* field[0] = device_condition */
};
static const ProtobufCIntRange device_condition__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor device_condition__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DeviceCondition",
  "DeviceCondition",
  "DeviceCondition",
  "",
  sizeof(DeviceCondition),
  2,
  device_condition__field_descriptors,
  device_condition__field_indices_by_name,
  1,  device_condition__number_ranges,
  (ProtobufCMessageInit) device_condition__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor attestation_state__field_descriptors[3] =
{
  {
    "attestation_state",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(AttestationState, attestation_state),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aid",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AttestationState, aid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vid",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AttestationState, vid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned attestation_state__field_indices_by_name[] = {
  1,   /* field[1] = aid */
  0,   /* field[0] = attestation_state */
  2,   /* field[2] = vid */
};
static const ProtobufCIntRange attestation_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor attestation_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AttestationState",
  "AttestationState",
  "AttestationState",
  "",
  sizeof(AttestationState),
  3,
  attestation_state__field_descriptors,
  attestation_state__field_indices_by_name,
  1,  attestation_state__number_ranges,
  (ProtobufCMessageInit) attestation_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
